// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1vcC8Z1O7ixUlT_FxxQ5M3JA08fG4YT8',
    appId: '1:869278023206:web:2e34b23718c11c4b4bf0e7',
    messagingSenderId: '869278023206',
    projectId: 'pinda-62fde',
    authDomain: 'pinda-62fde.firebaseapp.com',
    storageBucket: 'pinda-62fde.firebasestorage.app',
    measurementId: 'G-0XHMGW3TK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCot4KDp43RH761ZE_hjIfiQeMG-Pbgzho',
    appId: '1:869278023206:android:447571a437d5678d4bf0e7',
    messagingSenderId: '869278023206',
    projectId: 'pinda-62fde',
    storageBucket: 'pinda-62fde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMD8BRU1BHT96f0novGEsT2XyGJOE0mcY',
    appId: '1:869278023206:ios:2b7e7118f4135b784bf0e7',
    messagingSenderId: '869278023206',
    projectId: 'pinda-62fde',
    storageBucket: 'pinda-62fde.firebasestorage.app',
    iosBundleId: 'com.example.myLocation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMD8BRU1BHT96f0novGEsT2XyGJOE0mcY',
    appId: '1:869278023206:ios:2b7e7118f4135b784bf0e7',
    messagingSenderId: '869278023206',
    projectId: 'pinda-62fde',
    storageBucket: 'pinda-62fde.firebasestorage.app',
    iosBundleId: 'com.example.myLocation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1vcC8Z1O7ixUlT_FxxQ5M3JA08fG4YT8',
    appId: '1:869278023206:web:d5de22edca72efab4bf0e7',
    messagingSenderId: '869278023206',
    projectId: 'pinda-62fde',
    authDomain: 'pinda-62fde.firebaseapp.com',
    storageBucket: 'pinda-62fde.firebasestorage.app',
    measurementId: 'G-PVT67LPCCW',
  );
}
