name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - run: flutter config --enable-web
      - run: flutter pub get
      
      # 중요: GitHub Pages 리포지토리 이름(Pinda_MVP)에 맞춰 base-href 설정
      - run: flutter build web --release --web-renderer html --base-href "/Pinda_MVP/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
